### ISSUE TITLE
NPM package import doesn't work

### ISSUE THREAD

**Issue by MattIPv4** [do-community/glob-tool#22]
## Information

N/A -- reproduced across multiple browsers.

### Description 

Importing files from an NPM package does not work.

### Steps to reproduce

1. Open the tool
2. Click the import from NPM button
3. Enter a package name (eg. `vue`)
4. Observe error message & error in console

### Expected behavior

This works correctly in development, only the production build with scope hoisting fails.
The call to `inflate` from pako is the source of the issue -- it might be worth trying to find an alternative for extracting the tar?

### Screenshots

N/A

**Comment by MattIPv4** [comment]
So, after much digging, I have the following:

- I replaced `pako` with `gunzip-maybe`. This didn't fix it, but gunzip-maybe is lighter I believe
- I then went to disable minification and enable source maps to better diagnose the issue. Upon loading the tool and trying NPM import, it worked?!

The conclusion I've reached based on this after a bit more playing around is that Parcel's minification is breaking the tool. I have no idea how... my next step is to look at changing `do-vue` to use a secondary package to handle minifying JS.

**Comment by MattIPv4** [comment]
Upon further investigation, whilst the use of `gunzip-maybe` is smaller, it requires the `Buffer` polyfill, which makes the bundle larger. As such, I'll revert back to `pako`.

However, I have a branch of `do-vue` stood up now with Terser instead of Parcel's built-in minification. This resolves the error seen before & seems to actually result in smaller bundle size (467.77 -> 463.77).

**Comment by Glennmen** [comment]
@MattIPv4 Isn't the issue that you are trying to use node libraries in the browser? 🤔 And therefor parcel is removing methods/parts (incorrectly) that it thinks are not needed.

**Comment by MattIPv4** [comment]
@Glennmen It could be that Parcel is doing some funky tree shaking. However, if you simply disable Parcel's minification, leaving tree shaking on etc., this error disappears. So I'm very confident its something about the minification logic Parcel is using that's causing the issue, not tree shaking.
