### ISSUE TITLE
strings doesn't match if there is a dot in the path

### ISSUE THREAD

**Issue by djiangnz** [do-community/glob-tool#54]
## Information

https://whatismybrowser.com/w/G5DXQC3

### Problem

strings doesn't match if there is a dot in the path

### Screenshots

<img width="405" alt="image" src="https://user-images.githubusercontent.com/14226783/172249926-d42c1fe2-4d00-4e72-a050-9163d21df7aa.png">

**Comment by MattIPv4** [comment]
This is the default behaviour of globs in the real world:

```
mkdir .test
echo "hello" > .test/test.txt

mkdir test
echo "world" > test/test.txt

cat **/*.txt
world

cat {.test,test}/*.txt
hello
world
```

That being said, minimatch does have an option to allow dot-file matching, so we might as well add an off-by-default checkbox to the tool to allow this kind of matching by default: https://github.com/isaacs/minimatch#dot
