### ISSUE TITLE
add an ignore paths field

### ISSUE THREAD

**Issue by skeddles** [do-community/glob-tool#66]
## Feature request

add an ignore paths field

### Feature description
add a box to put it paths that should be ignored

### How the feature is useful
ignore paths are used to subtract from the matched paths, and is sometimes required.

**Comment by webketje** [comment]
Are you sure negated matches aren't sufficient? eg [example](https://www.digitalocean.com/community/tools/glob?comments=false&glob=%21%2A%2A%2F%2A%7B.md%2C.html%7D&matches=false&tests=blog%2Findex.md&tests=blog%2Fposts%2Fpost-1.md&tests=blog%2Fposts%2Fpost-2.md&tests=blog%2Fpost-outside.md&tests=services%2Fwebdesign%2Findex.md&tests=services%2Femail%2Findex.html&tests=about.md&tests=css%2Fstyle.css&tests=js%2Fsite.js&tests=index.md&tests=404.md)
If not negated matches, this is not really a "glob tool" feature but a "filelist processing" feature (and a separate step, so perhaps outside of the scope of this tool).

**Comment by MattIPv4** [comment]
Negated matches are supported, I don't see reason to also have a dedicated input that essentially does the same thing.
