### ISSUE TITLE
Unable to build glob-tool

### ISSUE THREAD

**Issue by acjohnson** [do-community/glob-tool#85]
## Information
https://www.whatismybrowser.com/w/BSYJJT9

### Description 
Whenever I try to build (using node 20 but I've tested node 16 and 18 as well)

```shell
# npm install
# npm run build
```
I get following error
```shell
> glob-tool@1.0.0 build
> npm run build:clean && npm run build:template && npm run build:static && npm run build:tool


> glob-tool@1.0.0 build:clean
> do-vue clean

Cleaning out dist directory...
...dist directory cleaned for build.
(node:4785) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

> glob-tool@1.0.0 build:template
> do-vue template

Fetching Community Tools template from www.digitalocean.com...
Unhandled rejection at: Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'parentElement')
      at module.exports (/home/acjohnson/glob-tool/node_modules/do-vue/src/build/fetchTemplate.js:141:65)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
TypeError: Cannot read properties of null (reading 'parentElement')
    at module.exports (/home/acjohnson/glob-tool/node_modules/do-vue/src/build/fetchTemplate.js:141:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps to reproduce
Download the latest node LTS, extract, clone the glob-tool repo, and attempt to build
```shell
# tar xf node-v20.11.0-linux-x64.tar.xz 
# export PATH=/home/acjohnson/Downloads/node-v20.11.0-linux-x64/bin:$PATH
# git clone https://github.com/do-community/glob-tool.git
# cd glob-tool/
# npm install
# npm run build
```

### Expected behavior
glob-tool should build as normal

### Additional information
This was working for me earlier in the week, but now I am unable to get it to build and am unsure what changed... I've tried on other machines and still cannot build glob-tool...

**Comment by MattIPv4** [comment]
I've actually got an internal ticket filed to look at this, probably next week. I suspect a change happened in the structure of the DigitalOcean site, which https://github.com/do-community/do-vue/blob/master/src/build/fetchTemplate.js parses to get a base HTML page for building the tools including this one.

As a workaround for now, you can update the `build:template` script here to call `BLANK_TEMPLATE=true do-vue template`, which should skip using the DigitalOcean site as the base.

**Comment by MattIPv4** [comment]
I should, of course, also note that the live version of the tool is still up and running, so you can access it at https://do.co/glob-tool just fine still.

**Comment by acjohnson** [comment]
`BLANK_TEMPLATE=true do-vue template` works for me, thanks!
